# Generated by Django 3.2.8 on 2021-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='messages',
            field=models.TextField(),
        ),
    ]
