# Generated by Django 3.2.8 on 2021-11-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_poost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Poost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
